<?php

namespace AppBundle\Repository;

/**
 * CredibilityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CredibilityRepository extends \Doctrine\ORM\EntityRepository
{
}
