<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{

	public function findOpenEvents() {
		return $this->createQueryBuilder( 'q' )->where( 'q.closedAt IS NULL' )->getQuery()->execute();
	}

}
