<?php

namespace AppBundle\Repository;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MisinformationRepository extends \Doctrine\ORM\EntityRepository
{

	public function getBulos($eventId, $lastId){

		return $this->createQueryBuilder( 'q' )->where( 'q.event = :event' )->andWhere( 'q.obtainedAt > :last' )
		            ->setParameters( array( 'event' => $eventId, 'last' => $lastId ) )->orderBy('q.obtainedAt')->setMaxResults(1)->getQuery()->execute();

	}

}
