<?php

namespace AppBundle\Repository;

/**
 * SourceTypesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SourceTypesRepository extends \Doctrine\ORM\EntityRepository
{
}
